language: julia
os:
  - linux

notifications:
  email: false

script:
  - julia --project --check-bounds=yes -e 'import Pkg; Pkg.build(); Pkg.test("ScoreDrivenExponentialRandomGraphs"; coverage=true)'

