name = "ScoreDrivenExponentialRandomGraphs"
uuid = "6ee3d76e-adae-4ed7-a671-0c83eafad244"
authors = ["Domenico Di Gangi <digangidomenico@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.5"

[targets]
test = ["Test"]
